import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Top-left name branding */}
        <div
          className="fixed top-6 left-7 z-50 font-bold text-white text-xl drop-shadow-lg select-none text-stroke-2 text-stroke-black"
          style={{ fontFamily: 'Helvetica Bold, Helvetica, Arial, sans-serif' }}
        >
          Ganti Akhil Sai
        </div>
        {children}
      </body>
    </html>
  );
}
